### ISSUE TITLE
ubuntu 16.04 x64 build attempt - cannot get sublime text to use numpy

### ISSUE THREAD

**Issue by gibacic** [komsit37/sublime-q#12]
I started using `sublime-q` on OS X, got hooked, and now I want to use it on Linux (since I cannot install most of the software I want to use on OS X anymore), but I cannot get `numpy` to be recognised by `Sublime Text 3 v3114`.

Not to be a bother, but I didn't know how else to contact you and figured you might be able to tell me if I have made a simple mistake in my installation.

I've built `numpy-1.8.1` from source using `Python 3.3` as instructed, copied it to `~/.config/sublime-text-3/Packages/numpy`, and checked to see that `Sublime Text 3` and `Package Control` sees that it is installed. I then installed `sublime-q`.

Each time on startup, Sublime Text returns the following in the console after loading my other plugins, `numpy` and `sublime-q`:

> `...`
> `plugins loaded`
> `Package Control: Installing 1 missing dependency`
> `Package Control: The dependency "numpy" is either not available on this platform or for this version of Sublime Text`
> `Package Control: Installed missing dependency numpy`
> `Package Control: Skipping automatic upgrade, last run at 2016-07-08 11:51:45, next run at 2016-07-08 12:51:45 or after`
> `error: Package Control`
> `1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.`

I cannot connect to my local `q` session after this.

I also get this error if I copy the `numpy` folder to `~/.config/sublime-text-3/Packages/lib/linux_x64/` or `~/.config/sublime-text-3/lib/linux_x64/`.

Is something broken in `Sublime Text 3` or `Package Control` that's keeping me from using `sublime-q` properly? I appreciate any help you can lend.

Thanks,
Goran

**Comment by komsit37** [comment]
sorry the document in README was a bit misleading. The process to add numpy has changed since. now it is a package dependencies.

quick steps
1. add numpy linux in sublime-numpy repo, you'll need to send PR to add linux numpy to https://github.com/komsit37/sublime-numpy (under st3_linux_x64)
2. tell package control that we now have numpy linux and sublime-q supports linux. in package control repo, 
send PR to add linux platform support to 
https://github.com/wbond/package_control_channel/blob/master/repository/dependencies.json
(search for numpy package and add linux-x64 to platforms)
and
https://github.com/wbond/package_control_channel/blob/master/repository/q.json
(search for q KDB package and add linux-x64 to platforms)
1. support linux keymap in sublime-q repo, add Linux keymap similiar to https://github.com/komsit37/sublime-q/blob/master/sublime/Default%20(OSX).sublime-keymap

some more explanation on how these work
when you install sublime-q, package control will try to download all the dependencies specified here https://github.com/komsit37/sublime-q/blob/master/dependencies.json
then it will look up numpy dependencies from here https://github.com/wbond/package_control_channel/blob/master/repository/dependencies.json
next, it will download latest release from https://github.com/komsit37/sublime-numpy/releases

more info regarding dependencies
https://packagecontrol.io/docs/dependencies
more details specific to this plugin dependencies
https://github.com/wbond/package_control_channel/pull/5156

**Comment by gibacic** [comment]
Thanks for the detailed reply!

I've submitted the three pull requests you suggested.

I'm still relatively new to building my own software from source so I greatly appreciate the clarification. I'll report back about `sublime-q`'s behaviour on my system when the requests are accepted and I have everything up and running.

Thanks again

**Comment by komsit37** [comment]
Great, thanks for contributing! I have merged your PRs. It is quite complicate to build sublime plugin, especially the dependency part, and there is not much document available. So let me know if you need any help!

**Comment by komsit37** [comment]
I assume linux version is working now. So I will just close the issue. Feel free to reopen if you still have any issue.
