### ISSUE TITLE
large number return causes kdb 3.6 to crash

### ISSUE THREAD

**Issue by pindash** [komsit37/sublime-q#17]
60000000000 in sublime causes q to crash with wsfull

I'm using sublime-q  version 0.2.11

KDB version 3.6 2018.07.30
on red hat 6.6

**Comment by hongshaoyang** [comment]
+1. reproducible on:

- sublime-q 0.2.11
- KDB version 3.5 2017.09.06
- Red Hat Enterprise Linux (RHEL) Server 7.5

Does not occur if using [qpad 1.8](http://qinsightpad.com)

**Comment by komsit37** [comment]
@pindash @hongshaoyang Thanks for reporting. 

This is caused by my custom q code wrapper which tries to figure out table dimension from the result.
In short, it tries to to execute `cols 60000000000` and got `'wsfull`. The code is in this line:
https://github.com/komsit37/sublime-q/blob/master/q_send.py#L47

Calling `cols` on non table-like data (i.e. long) will raise error (so I wrap it in trap), but it shouldn't cause `'wsfull`. Anyway, I will find workaround for this.

**Comment by komsit37** [comment]
I've released the fix. Package Control should automatically pickup the latest version soon.

**Comment by pindash** [comment]
Thank you. I had been using your plugin for a long time without issue but
always with 3.4, so that makes total sense.
